### ISSUE TITLE
Crash w/ SwampierSwamps

### ISSUE THREAD

**Issue by GamerGaven** [frikinjay/morefrogs#10]
I'm dropping this here because this mod and SwampierSwamps both add frog variants, that seems to be causing this crash to occur. I opened an issue on their github, https://github.com/andrew0030/SwampierSwamps/issues/6, and now leaving this here in hopes of 
potentially resolving it. :)
[latest.log](https://github.com/frikinjay/morefrogs/files/9749822/latest.log)

**Comment by andrew0030** [comment]
Hey there, Im the Swampier Swamps Dev!
My theory is there is something happening between my FrogMixin and the one from More Frogs.
Ofc this is just an assumption as I cant look at yours, but I would be happy to discuss this issue and find a solution!
That said, it would be nice if you could share your FrogMixin code with me!

**Comment by andrew0030** [comment]
Hey there its me again!
So I looked into it, and I am pretty sure this is caused due to the usage of an **Overwrite** Mixin on your end. Ofc I may be wrong, but I will just be a little proactive and assume this is the case!

Ok, so assuming you are determining your Frog Variants the same way Minecraft and I do, you are just using an if statement inside the Frogs "finalizeSpawn" method, and you added it using Overwrite.
If this is the case I have a better solution that will ensure compatibility with other Mods!
Basically what I do is ([this](https://github.com/andrew0030/SwampierSwamps/blob/43f0f34cf1fe85c7ee4e4d7646b6c082aecc352c/src/main/java/andrews/swampier_swamps/mixins/frog/FrogMixin.java#L22-L90))
The idea is instead of Overwriting the method, (which is a big nono because Overwrite breaks all other mods that mixin into the method) I simply inject an if statement right before Minecraft calls "**initMemories**" and after the Minecraft Variants got assigned.
This ensures a few things:
 - If for SOME reason _and I cant think of one maybe a typo_ applying the Mods variant fails, it will use the vanilla one instead as it got applied already!
 - This way it will remain fully compatible with all other Mods that do this. The only issue is if say all Mods added Frogs to the same Biome. In that case the one that added its Variants last would be the one that gets spawned. That said this is really not a big deal because Biomes can be customized and altered based on the Mods installed to make all variants have a unique Biome.
 
If I am right, please do feel free to copy my Mixin. I think its important for Mod Devs to work together, to achieve compatibility between as many Mods as possible!

**Comment by frikinjay** [comment]
Hey, this has already been fixed in the fabric version I just havent found the motivation to port the fix to the forge version. I will probably fix it in a day or so. Thanks for reaching out.

**Comment by andrew0030** [comment]
Sounds good!

**Comment by frikinjay** [comment]
fixed in forge 1.1.1 release
